# netlify.toml (Final Version)

[build]
  publish = "."
  functions = "netlify/functions"

# Specific settings ONLY for the generate-bulk-cards function
[functions."generate-bulk-cards"]
  # Include the browser files with this function
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

# Add this section back to use a compatible server environment
[images]
  build_image_selection = "jammy"