# ============================================================
# netlify.toml ฉบับแก้ไขสุดท้าย (Root Folder Strategy)
# ============================================================

[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# --- การตั้งค่าสำหรับแต่ละฟังก์ชัน ---

# (A) ตั้งค่าให้ฟังก์ชัน generate-bulk-pdf "รวม" โฟลเดอร์ fonts จาก root
[functions."generate-bulk-pdf"]
  # Path นี้จะชี้ไปที่โฟลเดอร์ fonts ที่อยู่ใน Root ของโปรเจกต์
  included_files = ["fonts/**"]

# (B) ตั้งค่าให้ฟังก์ชัน generate-bulk-cards "รวม" Chromium ไปด้วย
[functions."generate-bulk-cards"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]
