[build]
  publish = "."
  command = "echo 'No build step required'"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  
[functions]
  directory = "netlify/functions"
  external_node_modules = ["playwright-core", "playwright-aws-lambda"]
  
  [functions."generate-print-pdf"]
    included_files = [
      "node_modules/playwright-aws-lambda/**/*",
      "node_modules/playwright-core/**/*"
    ]
  
  [functions."generate-bulk-cards"]
    included_files = [
      "node_modules/playwright-aws-lambda/**/*",
      "node_modules/playwright-core/**/*"
    ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.development.environment]
  NODE_ENV = "development"
  NETLIFY_DEV = "true"
