# Netlify Build & Deploy Settings

[build]
  # Directory to publish (root of the project)
  # บอกให้ Netlify รู้ว่าไฟล์ HTML ทั้งหมดอยู่ที่โฟลเดอร์หลัก
  publish = "."
  
  # Directory where our serverless functions live
  # บอกให้ Netlify รู้ว่าฟังก์ชัน Backend ทั้งหมดอยู่ที่นี่
  functions = "netlify/functions"

# --- ไม่ต้องมีส่วน [[redirects]] อีกต่อไป ---

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-eval' blob: https://unpkg.com https://cdn.jsdelivr.net https://ajax.googleapis.com; object-src 'none';"