# netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Settings for serverless functions
[functions]
  node_bundler = "esbuild"
  # FIX: Tell Netlify to include the chromium binary files in the function bundle
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

[images]
  # Use the "jammy" build image (Ubuntu 22.04)
  build_image_selection = "jammy"