# ============================================================
# นี่คือ netlify.toml ฉบับที่แก้ไขและรวมทุกอย่างถูกต้องแล้ว
# ให้ใช้ไฟล์นี้แทนที่ไฟล์เดิมทั้งหมด
# ============================================================

# (1) การตั้งค่า Build ทั่วไป (ส่วนนี้ถูกต้องอยู่แล้ว ไม่ต้องแก้ไข)
[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"


# (2) การตั้งค่าสำหรับแต่ละฟังก์ชันที่ต้องการไฟล์เพิ่มเติม
# เราจะใช้รูปแบบ [[functions]] ที่ถูกต้องเพียงรูปแบบเดียวเท่านั้น

# --- ตั้งค่าสำหรับฟังก์ชันที่สร้าง PDF และต้องใช้ฟอนต์ ---
[[functions]]
  name = "generate-bulk-pdf"
  # Path นี้ต้องตรงกับที่ระบุในโค้ด JavaScript ของคุณ
  # และเป็น path จาก root ของโปรเจกต์
  included_files = ["netlify/functions/fonts/**"]

# --- ตั้งค่าสำหรับฟังก์ชันที่สร้าง Card และต้องใช้ Chromium/Puppeteer ---
[[functions]]
  name = "generate-bulk-cards"
  # Path นี้อ้างอิงจาก node_modules ใน root ของโปรเจกต์
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

# หากมีฟังก์ชันอื่นที่ต้องการการตั้งค่าพิเศษในอนาคต
# คุณสามารถเพิ่มบล็อก [[functions]] ต่อท้ายไปได้เรื่อยๆ
