# ============================================================
# netlify.toml ฉบับแก้ไขล่าสุดตาม Error Log
# ใช้ไฟล์นี้แทนที่ไฟล์เดิมทั้งหมด
# ============================================================

# (1) การตั้งค่า Build ทั่วไป (ส่วนนี้ถูกต้องอยู่แล้ว)
[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# (2) การตั้งค่าสำหรับแต่ละฟังก์ชันที่ต้องการไฟล์เพิ่มเติม
# เราจะใช้รูปแบบ [functions."ชื่อฟังก์ชัน"] ซึ่งเป็นรูปแบบ Object ที่ถูกต้อง

# --- ตั้งค่าสำหรับฟังก์ชัน generate-bulk-pdf ให้รวมฟอนต์ไปด้วย ---
[functions."generate-bulk-pdf"]
  included_files = ["netlify/functions/fonts/**"]

# --- ตั้งค่าสำหรับฟังก์ชัน generate-bulk-cards ให้รวม Chromium ไปด้วย ---
[functions."generate-bulk-cards"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

# หากมีฟังก์ชันอื่นที่ต้องการการตั้งค่าพิเศษในอนาคต
# ให้เพิ่มบล็อก [functions."ชื่อฟังก์ชันอื่น"] ต่อท้ายไปได้เรื่อยๆ
