# netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# General settings for all functions
[functions]
  node_bundler = "esbuild"

# FIX: Specific settings ONLY for the generate-bulk-cards function
[functions."generate-bulk-cards"]
  # Tell Netlify to include the chromium binary files ONLY for this function
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

[images]
  build_image_selection = "jammy"