# /netlify.toml - Final Consolidated Version

# (1) These are your existing general build settings, which are correct.
[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# (2) This is your existing setting for a function that needs Chromium.
# It remains unchanged.
[functions."generate-bulk-cards"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

# (3) *** THIS IS THE NEW, CRUCIAL PART ***
# This adds a new, specific setting for our PDF generation function.
# It tells Netlify to include the 'fonts' directory for 'generate-bulk-pdf'.
[functions."generate-bulk-pdf"]
  included_files = ["fonts/**"]
