# netlify.toml (Simplified for testing)

[build]
  publish = "."
  functions = "netlify/functions"

# Specific settings ONLY for the generate-bulk-cards function
[functions."generate-bulk-cards"]
  # We still need to tell Netlify to include the browser files.
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]