# netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions."generate-bulk-cards"]
  # This line is still needed to include the browser files
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]