# /netlify.toml - Final Consolidated Version

# (1) These are your existing general build settings, which are correct.
[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# (2) This is your existing setting for a function that needs Chromium.
# It remains unchanged.
[functions."generate-bulk-cards"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

# (3) *** THIS IS THE NEW, CRUCIAL PART ***
# This adds a new, specific setting for our PDF generation function.
# It tells Netlify to include the 'fonts' directory for 'generate-bulk-pdf'.
[functions."generate-bulk-pdf"]
  included_files = ["fonts/**"]


# กำหนดค่าสำหรับฟังก์ชัน generate-bulk-pdf โดยเฉพาะ
[[functions]]
  # ชื่อฟังก์ชันต้องตรงกับชื่อไฟล์ (ไม่รวม .js)
  name = "generate-bulk-pdf"
  
  # นี่คือบรรทัดที่สำคัญที่สุดสำหรับแก้ปัญหานี้
  # บอกให้ Netlify นำไฟล์ทั้งหมดในโฟลเดอร์ fonts ไปด้วย
  included_files = ["netlify/functions/fonts/**"]

# คุณอาจมีส่วนตั้งค่าสำหรับฟังก์ชันอื่นๆ ด้วย เช่น
# [[functions]]
#   name = "generate-bulk-cards"
#   included_files = ["node_modules/@sparticuz/chromium/bin/**"]