# Netlify Build & Deploy Settings

[build]
  # Directory to publish (root of the project)
  publish = "."
  
  # Directory where our serverless functions live
  functions = "netlify/functions"

# Add this section to specify the build image
[images]
  # Use the "jammy" build image (Ubuntu 22.04)
  # This is the crucial fix for the missing library error
  build_image_selection = "jammy"